language: node_js
node_js:
  - '6'
  - '7'

before_script:
  - sudo apt-get install build-essential -y
  - sudo npm install -g npm
  - sudo apt-get install -qq python-numpy python-scipy
  - sudo npm install -g bit-bin

before_install:
  - node --version


addons:
  apt:
    packages:
      - git

branches:
  only:
  - master
  - stable

cache:
  directories:
  - node_modules
  - lib
  - lib-legacy

os:
  - linux
